version: '3.4'

services:
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    expose:
      - "8080"

  teashopservice:
    build:
      context: .
      dockerfile: TeaShopService/Dockerfile
    ports:
      - "${TEASHOP_HTTP_PORT}:8080"
    depends_on:
      - orderservice

