version: '3.4'

services:
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    expose:
      - "8080"

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - orderservice

