version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        SA_PASSWORD: MyPassw0rd!
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
  orderservice:
    build:
      context: ./OrderService
      dockerfile: OrderService/Dockerfile
    environment:
      #extract the password to a .env later
      ConnectionStrings__Default: "Server=sqlserver;Database=OrdersDb;User=sa;Password=MyPassw0rd!;Encrypt=false;TrustServerCertificate=true"
    expose:
      - "8080"
    depends_on:
      - sqlserver

  userservice:
      build:
        context: ./UserService
        dockerfile: UserService.API/Dockerfile
      environment:
        ConnectionStrings__Default: "Server=sqlserver;Database=UsersDb;User=sa;Password=MyPassw0rd!;Encrypt=false;TrustServerCertificate=true"
      expose:
        - "8080"
      depends_on:
        - sqlserver
      volumes:
        - ./rsa:/app/rsa:ro

  catalogservice:
    build:
      context: ./CatalogService
      dockerfile: CatalogService.API/Dockerfile
    environment:
      ConnectionStrings__Default: "Server=sqlserver;Database=CatalogDb;User=sa;Password=MyPassw0rd!;Encrypt=false;TrustServerCertificate=true"
    expose:
      - "8080"
    depends_on:
      - sqlserver
    volumes:
      - ./rsa/public.pem:/app/rsa/public.pem:ro


  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      userservice:
         condition: service_started
      orderservice:
         condition: service_started
      catalogservice:
         condition: service_started

      

 
  
  
